Add confirmation dialog for set and generate commands

diff --git a/aws/.local/bin/secret b/aws/.local/bin/secret
--- a/aws/.local/bin/secret
+++ b/aws/.local/bin/secret
@@ -33,6 +33,19 @@ Examples:
 EOF
 }
 
+confirm() {
+  while true; do
+    echo "This operation will overwrite the value of $1"
+    echo "Are you sure? (y/n)"
+    read -r CONFIRM
+    case $yn in
+      [Yy]* ) echo "Aborting"; exit 1;;
+      [Nn]* ) break;;
+      * ) echo "Please answer y/n.";;
+    esac
+  done
+}
+
 
 get_secret() {
   if [ -z $AWS_PROFILE ]; then
@@ -61,6 +74,7 @@ generate_secret() {
     LENGTH=$2
     SECPATH=$1
   fi
+  confirm
 
   echo "Generating password"
   GENERATED=$(pwgen -s $LENGTH 1)
@@ -76,10 +90,10 @@ set_secret() {
     echo "Missing path to secret or value"
     exit 1
   fi
+  confirm
 
   echo "Putting value to $1"
   aws ssm put-parameter --name $1 --value $2 --type SecureString --overwrite >/dev/null
-  aws ssm get-parameter --name $1 --with-decryption --outuput text --query Parameter.Value | cat
 }
 
 find_secret() {
