Fixup

diff --git a/aws/.local/bin/secret b/aws/.local/bin/secret
--- a/aws/.local/bin/secret
+++ b/aws/.local/bin/secret
@@ -38,9 +38,9 @@ confirm() {
     echo "This operation will overwrite the value of $1"
     echo "Are you sure? (y/n)"
     read -r CONFIRM
-    case $yn in
-      [Yy]* ) echo "Aborting"; exit 1;;
-      [Nn]* ) break;;
+    case $CONFIRM in
+      [Nn]* ) echo "Aborting"; exit 1;;
+      [Yy]* ) break;;
       * ) echo "Please answer y/n.";;
     esac
   done
@@ -74,7 +74,7 @@ generate_secret() {
     LENGTH=$2
     SECPATH=$1
   fi
-  confirm
+  confirm $1
 
   echo "Generating password"
   GENERATED=$(pwgen -s $LENGTH 1)
@@ -90,7 +90,7 @@ set_secret() {
     echo "Missing path to secret or value"
     exit 1
   fi
-  confirm
+  confirm $1
 
   echo "Putting value to $1"
   aws ssm put-parameter --name $1 --value $2 --type SecureString --overwrite >/dev/null
