Add generate feature to secret

diff --git a/aws/.local/bin/secret b/aws/.local/bin/secret
--- a/aws/.local/bin/secret
+++ b/aws/.local/bin/secret
@@ -16,6 +16,7 @@ Available Commands:
   find        Find secrets in AWS SSM Parameter Store
   get         Retrieve a secret from AWS SSM Parameter Store
   set         Store or overwrite a secret in AWS SSM Parameter Store
+  generate    Generate a password and store it in AWS SSM Parameter Store, takes password length as a parameter
   help        Shows this help message
 
 Flags:
@@ -27,6 +28,7 @@ Examples:
   secret -r us-east-1 set /path/to/secret [value]
   secret get /path/to/secret
   secret set /path/to/secret [value]
+  secret generate /path/to/secret 36
 
 EOF
 }
@@ -34,7 +36,7 @@ EOF
 
 get_secret() {
   if [ -z $AWS_PROFILE ]; then
-    AWS_PROFILE=$(_awsp)
+    export AWS_PROFILE=$(_awsp)
   fi
   if [ $# -eq 0 ]; then
     echo "Missing path to secret"
@@ -44,9 +46,31 @@ get_secret() {
   aws ssm get-parameter --name $1 --with-decryption --output text --query Parameter.Value | cat
 }
 
+generate_secret() {
+  if [ -z $AWS_PROFILE ]; then
+    export AWS_PROFILE=$(_awsp)
+  fi
+  if [ $# -lt 2 ]; then
+    echo "Missing length of password, defaulting to 36"
+    LENGTH=36
+    if [ $# -eq 0 ]; then
+      echo "Missing path to secret"
+      exit 1
+    fi
+  else
+    LENGTH=$2
+    SECPATH=$1
+  fi
+
+  echo "Generating password"
+  GENERATED=$(pwgen -s $LENGTH 1)
+  aws ssm put-parameter --name $1 --value ${GENERATED} --type SecureString --overwrite >/dev/null
+  echo "Password generated and stored in $1"
+}
+
 set_secret() {
   if [ -z $AWS_PROFILE ]; then
-    AWS_PROFILE=$(_awsp)
+    export AWS_PROFILE=$(_awsp)
   fi
   if [$# -lt 2 ]; then
     echo "Missing path to secret or value"
@@ -60,7 +84,7 @@ set_secret() {
 
 find_secret() {
   if [ -z $AWS_PROFILE ]; then
-    AWS_PROFILE=$(_awsp)
+    export AWS_PROFILE=$(_awsp)
   fi
   if [ $# -eq 0 ]; then
     echo "Missing search term"
@@ -71,7 +95,7 @@ find_secret() {
 
 list_secrets() {
   if [ -z $AWS_PROFILE ]; then
-    AWS_PROFILE=$(_awsp)
+    export AWS_PROFILE=$(_awsp)
   fi
   aws ssm describe-parameters | jq -r '.Parameters[].Name'
 }
@@ -106,6 +130,11 @@ while [[ $# -gt 0 ]]; do
     find)
       shift
       find_secret $@
+      exit 0
+      ;;
+    generate)
+      shift
+      generate_secret $@
       exit 0
       ;;
     -p|--profile)
